app = "solymar-dashboard"
primary_region = "iad" 

[deploy]
  release_command = "./node_modules/.bin/prisma migrate deploy"
  seed_command = "ts-node -T prisma/seed.ts"

[http_service]
  auto_start_machines = true
  auto_stop_machines = true
  force_https = true
  internal_port = 3000
  min_machines_running = 0 
  processes = ["app"]
  [[http_service.checks]]
    grace_period = "30s"
    interval = "15s"
    timeout = "2s"
    method = "GET"
    path = "/api"   # Apunta a /api porque tienes setGlobalPrefix('api')

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024