app = "solymar-dashboard"
primary_region = "iad"

[deploy]
  release_command = "./node_modules/.bin/prisma migrate deploy"
  seed_command = "ts-node -T prisma/seed.ts"

# Configuración de la Máquina (Hardware)
[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory = "1gb"
  memory_mb = 1024

# Configuración de Servicios (Red) - La forma explícita
[[services]]
  protocol = "tcp"
  internal_port = 3000
  processes = ["app"]
  
  # Redirigir puerto 80 a HTTPS (Estándar)
  [[services.ports]]
    port = 80
    handlers = ["http"]
    force_https = true

  # Manejar puerto 443 (HTTPS)
  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  # Chequeo de Salud TCP (Básico y robusto)
  [[services.tcp_checks]]
    interval = "15s"
    timeout = "5s"       # Le damos 5s para responder al ping
    grace_period = "30s" # Esperamos 30s al arranque antes de molestar